spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: tien
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentu20905@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  ai:
    openai:
      # --- CẤU HÌNH CŨ (Giữ lại để phòng khi lỗi có thể quay lại) ---
      # api-key: ${GROQ_API_KEY}
      # base-url: https://api.groq.com/openai
      # chat:
      #   options:
      #     model: llama-3.3-70b-versatile
      
      # --- CẤU HÌNH MỚI: GEMINI 2.5 PRO ---
      api-key: ${GEMINI_API_KEY} 
      #api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/ # URL tương thích OpenAI của Google (Nếu dùng OpenRouter thì đổi thành https://openrouter.ai/api/v1)
      chat:
        options:
          model: gemini-2.5-flash # Nếu dùng OpenRouter thì đổi thành google/gemini-2.5-pro gemini-2.0-flash
                                  


server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret-key: ${JWT_SECRET}

vnpay:
  tmn-code: 4792TJ7Y
  secret-key: ${VNPAY_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:5173/payment/vnpay-return