spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: Nguyentu205@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentu20905@gmail.com
    password: pmeadadilyulpupb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8081
  servlet:
    context-path: /api

jwt:
  secret-key: 1fa10329547167709d24b3287b742dd287233b6bf4d36604e924dba849d05cf9b6b1d69d1f2493f1b26c5c28fd8e9366187decd7be4c4c90585235b7a5d79338

vnpay:
  tmn-code: 4792TJ7Y
  secret-key: I86EACU6F7UDSGB3XT7A6SH5DEESDRYV
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:5173/payment/vnpay-return